name: React Vite Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --force
          
      - name: Build project
        run: |
          npm run build
          echo "Build output:"
          ls -la dist/
          
      - name: Verify build output
        run: |
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Error: index.html not found in dist directory"
            ls -la dist/
            exit 1
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-build
          path: dist/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
